# Generated by Django 4.1.2 on 2022-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_event_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.TextField(default=""),
        ),
    ]
