# Generated by Django 4.1.2 on 2022-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_of_event",
            field=models.DateTimeField(),
        ),
    ]
