# Generated by Django 4.1.2 on 2022-10-25 01:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_event_created_by_event_user_alter_event_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.AlterField(
            model_name="event",
            name="organiser",
            field=models.CharField(
                default=django.contrib.auth.models.User, max_length=50
            ),
        ),
    ]
