# Generated by Django 4.1.2 on 2022-10-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_event_created_by_remove_event_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organiser",
            field=models.CharField(max_length=50),
        ),
    ]
