# Generated by Django 4.1.2 on 2022-10-25 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0010_alter_event_organiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
