# Generated by Django 4.1.2 on 2022-10-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_event_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="users",
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
