# Generated by Django 4.1.2 on 2022-10-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_signin_alter_event_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.DeleteModel(
            name="Signin",
        ),
    ]
