# Generated by Django 4.1.2 on 2022-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_event_organiser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_of_event",
            field=models.DateField(),
        ),
    ]
