# Generated by Django 4.1.2 on 2022-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_event_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="organiser",
            new_name="user",
        ),
    ]
