# Generated by Django 4.1.2 on 2022-10-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_rename_organiser_event_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="user",
            new_name="organiser",
        ),
    ]
