# Generated by Django 4.1.2 on 2022-10-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_rename_user_event_organiser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="bokkingstatus",
            new_name="bookingstatus",
        ),
    ]
