# Generated by Django 4.1.2 on 2022-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_rename_bokkingstatus_event_bookingstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="num_of_seats_booked",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
