# Generated by Django 4.1.2 on 2022-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_event_num_of_seats_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="bookingstatus",
            field=models.BooleanField(),
        ),
    ]
