# Generated by Django 4.1.2 on 2022-10-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_event_bookingstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="bookingstatus",
            new_name="booking_status",
        ),
    ]
