# Generated by Django 4.1.2 on 2022-10-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_rename_bookingstatus_event_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_status",
            field=models.BooleanField(null=True),
        ),
    ]
