# Generated by Django 4.1.2 on 2022-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_event_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="booking_status",
            field=models.BooleanField(default="False"),
        ),
    ]
